# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goship < Formula
  desc "SSH utility for AWS EC2 instances (find, ssh, tunnel etc)"
  homepage "https://github.com/zytek/goship"
  version "1.0.6-ztk4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/zytek/goship/releases/download/v1.0.6-ztk4/goship_1.0.6-ztk4_Darwin_x86_64.tar.gz"
    sha256 "48a751e9278b78c85b77a96a4df8591e87d1d52a0651974e8edb4202501ef47f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zytek/goship/releases/download/v1.0.6-ztk4/goship_1.0.6-ztk4_Linux_x86_64.tar.gz"
    sha256 "4b3ccc47c74af1f40e0508eeeeac8bd39abc2846976330a30375963992721666"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zytek/goship/releases/download/v1.0.6-ztk4/goship_1.0.6-ztk4_Linux_arm64.tar.gz"
    sha256 "83cd2270e27fd8cd71553a3092c3b61abcad4508957321ebbac714417f7f183c"
  end

  def install
    bin.install "goship"
  end

  test do
    system "#{bin}/goship version"
  end
end
