# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3perka < Formula
  desc "Utility that helps find, connect  and copy to particular cloud resources using configured providers"
  homepage "https://github.com/zytek/goship"
  version "0.2.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zytek/s3perka/releases/download/v0.2.2/s3perka_0.2.2_Darwin_x86_64.tar.gz"
    sha256 "f65855ad5a791f4fcf0a65559792ea0776f8a745874f7279404a07fbeba7e5cc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zytek/s3perka/releases/download/v0.2.2/s3perka_0.2.2_Linux_x86_64.tar.gz"
    sha256 "eb5c51ac820123ad4ac2cc0aa08671aee3c378966777a36e626028e61b09e5ad"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zytek/s3perka/releases/download/v0.2.2/s3perka_0.2.2_Linux_arm64.tar.gz"
    sha256 "a1c783b395dcae24cfa4c6959d2d6bff2b9f458e56ee2f6ab55d4a90cd158e7c"
  end

  def install
    bin.install "goship"
  end

  def caveats; <<~EOS
    You need to configure this software before use (goship configure or check docs)
  EOS
  end

  test do
    system "#{bin}/goship version"
  end
end
