# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3perka < Formula
  desc "Copy (sync) S3 objects between different AWS Partitions/Accounts"
  homepage "https://github.com/zytek/s3perka"
  version "0.2.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zytek/s3perka/releases/download/v0.2.3/s3perka_0.2.3_Darwin_x86_64.tar.gz"
    sha256 "1d0ad5eb08186a9c3c50f1b397eb6abff239ce942c60c42838658556302277c0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zytek/s3perka/releases/download/v0.2.3/s3perka_0.2.3_Linux_x86_64.tar.gz"
    sha256 "e83e5dd68c3cb1fd0a93af72f56ad52242cdb23cf4c12741fa41f67b9e5fe42e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zytek/s3perka/releases/download/v0.2.3/s3perka_0.2.3_Linux_arm64.tar.gz"
    sha256 "adf30ef5a8bbeee535f8c64c6dfb1d9dbaea42fbfcf4de1e2dcf8519a406624e"
  end

  def install
    bin.install "s3perka"
  end

  test do
    system "#{bin}/s3perka -h"
  end
end
