# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XchDownloader < Formula
  desc "Download utiity for xch-plotter.com"
  homepage "https://xch-plotter.com"
  version "0.5"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.5/xch-downloader_0.5_Darwin_x86_64.tar.gz"
    sha256 "7966791bcbc8d815d836825dea48fe0d578815bc95f31b8d05ee42f1c20655cd"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.5/xch-downloader_0.5_Darwin_arm64.tar.gz"
    sha256 "1e15dcd14607197706759393125a4630a232e695c8d46e6233f4344fbde76e02"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.5/xch-downloader_0.5_Linux_x86_64.tar.gz"
    sha256 "63c4eb2eca78713f5e6b9dd4e56ab4a0ac4d03c35c3bfce3ff80bb160bdf7af4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.5/xch-downloader_0.5_Linux_arm64.tar.gz"
    sha256 "d1f467e66e3c664bcc192ac37b31effb6c713ab6069f1ccca372f557a6cda6e9"
  end

  def install
    bin.install "xch-downloader"
  end

  test do
    system "#{bin}/xch-downloader"
  end
end
