# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XchDownloader < Formula
  desc "Download utiity for xch-plotter.com"
  homepage "https://xch-plotter.com"
  version "0.4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.4/xch-downloader_0.4_Darwin_x86_64.tar.gz"
    sha256 "31aa83c0ce9856f4cedf5a514724b52eae51acd7dbbd4bfcd60c5693f39f81c7"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.4/xch-downloader_0.4_Darwin_arm64.tar.gz"
    sha256 "8265fde6e367b4bfcebcc3ef6c695ff47b0a3decedcab1e897315988e556ed71"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.4/xch-downloader_0.4_Linux_x86_64.tar.gz"
    sha256 "9ae17bc321d865afe40f77989f8d89305f1ebeebb5bfc45ed9bfc92eb8c3b82b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zytek/xch-downloader/releases/download/v0.4/xch-downloader_0.4_Linux_arm64.tar.gz"
    sha256 "008b0909a65680102a83fba412923d0d4d673f7a2bf822d1386da9f5931e4330"
  end

  def install
    bin.install "xch-downloader"
  end

  test do
    system "#{bin}/xch-downloader"
  end
end
